import type { GalleryPhoto } from "@/components/photos-gallery/PhotosGallerySection";
import mediaUrls from "@/lib/media-urls";

export const websiteProjectsGalleryPhotos: GalleryPhoto[] = [

  // {
  //   src: mediaUrls.roots,
  //   alt: "Roots video örneği",
  //   title: "Roots",
  //   description: "Video örneği",
  //   tags: ["Video"],
  //   aspect: "square",
  //   mediaType: "video",
  //   profileName: "Ajans 99",
  //   profileIcon: "video",
  // },
  {
    src: mediaUrls.gallerima1,
    alt: "Profesyonel sosyal medya yönetimi video örneği",
    title: "Profesyonel Sosyal Medya Yönetimi",
    description: "Kısa video örneği",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "Social Media Pro",
    profileIcon: "camera",
    poster: mediaUrls.posters.gallerima1,
    country: "TR",
  },
  // {
  //   src: "/Deb.jpg",
  //   alt: "Instagram profil yönetimi örneği",
  //   title: "Instagram Profil Yönetimi",
  //   description: "Sosyal medya hesap yönetimi",
  //   tags: ["Social Media"],
  //   aspect: "square",
  //   mediaType: "image",
  //   profileName: "Social Media Pro",
  //   profileIcon: "camera",
  // },
  {
    src: mediaUrls.influencerWebm,
    alt: "Drone tanıtım videosu örneği",
    title: "Drone Tanıtım Videoları",
    description: "Kuș bakıșı tanıtım çekimleri",
    tags: ["Video", "Drone"],
    aspect: "square",
    mediaType: "video",
    profileName: "Drone Studios",
    profileIcon: "video",
    poster: mediaUrls.posters.influencer,
    country: "TR",
  },
  {
    src: mediaUrls.video1feedbird,
    alt: "Sosyal medya influencer içerik videosu",
    title: "Sosyal Medya İçerikleri",
    description: "Instagram & TikTok Reels",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "Content Studio",
    profileIcon: "sparkles",
    poster: mediaUrls.posters.video1feedbird,
    country: "TR",
  },
  // {
  //   src: mediaUrls.ticaret,
  //   alt: "E-ticaret ürün tanıtım videosu",
  //   title: "E-Ticaret Tanıtımı",
  //   description: "Ürün & mağaza videoları",
  //   tags: ["Video"],
  //   aspect: "square",
  //   mediaType: "video",
  //   profileName: "Commerce Studio",
  //   profileIcon: "rocket",
  // },
  {
    src: mediaUrls.villa,
    alt: "Lüks villa tanıtım videosu",
    title: "Villa Tanıtımı",
    description: "Lüks gayrimenkul videoları",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "Real Estate Media",
    profileIcon: "star",
    country: "TR",
  },
  {
    src: mediaUrls.konut,
    alt: "Konut projesi tanıtım videosu",
    title: "Konut Projesi Tanıtımı",
    description: "Emlak proje videoları",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "Real Estate Media",
    profileIcon: "lightbulb",
    country: "TR",
  },
  {
    src: mediaUrls.gallerima3Big,
    alt: "Sosyal medya içerik videosu",
    title: "Sosyal Medya İçerikleri",
    description: "Profesyonel video prodüksiyon",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "Ajans 99",
    profileIcon: "video",
    poster: mediaUrls.posters.gallerima3Big,
    country: "TR",
  },
  {
    src: mediaUrls.burger,
    alt: "Burger video örneği",
    title: "Burger",
    description: "Video örneği",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "Ajans 99",
    profileIcon: "video",
    poster: mediaUrls.posters.burger,
    country: "TR",
  },
  {
    src: mediaUrls.arsaCompressed,
    alt: "Arsa ve arazi tanıtım videosu",
    title: "Arsa Tanıtımı",
    description: "Yatırımlık arazi videoları",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "Land Media",
    profileIcon: "trophy",
    poster: mediaUrls.posters.arsaCompressed,
    country: "TR",
  },
  {
    src: mediaUrls.houston,
    alt: "Houston emlak tanıtım videosu",
    title: "Houston Emlak Tanıtımı",
    description: "ABD gayrimenkul videoları",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "Global Real Estate",
    profileIcon: "rocket",
    country: "US",
  },
  {
    src: mediaUrls.stories,
    alt: "Instagram stories içerik videosu",
    title: "Stories İçerikleri",
    description: "Instagram & Snapchat hikayeleri",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "Stories Studio",
    profileIcon: "camera",
    country: "TR",
  },
  {
    src: mediaUrls.video2,
    alt: "Influencer içerik üretimi videosu",
    title: "Influencer İçerik Videosu",
    description: "Sosyal medya içerik üretimi",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "Influencer Studio",
    profileIcon: "sparkles",
    country: "TR",
  },
  {
    src: mediaUrls.video3,
    alt: "Ürün tanıtım videosu",
    title: "Ürün Tanıtım Videosu",
    description: "Marka & ürün çekimleri",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "Product Media",
    profileIcon: "camera",
    country: "TR",
  },
  {
    src: mediaUrls.video4,
    alt: "Profesyonel reklam videosu",
    title: "Reklam Videosu",
    description: "Profesyonel reklam içerikleri",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "Ad Studio",
    profileIcon: "rocket",
    country: "TR",
  },
  // {
  //   src: mediaUrls.trr,
  //   alt: "Grafik tasarım örneği",
  //   title: "Özel Grafik Tasarımlar",
  //   description: "Markaya özel görsel çalışmalar",
  //   tags: ["Grafik"],
  //   aspect: "square",
  //   mediaType: "image",
  //   profileName: "Design Studio",
  //   profileIcon: "palette",
  // },
  // {
  //   src: "/video4_noaudio_trimmed.webm",
  //   alt: "Viral video animasyon örneği",
  //   title: "Viral Video İçerikleri",
  //   description: "Animasyon / reklam içerikleri",
  //   tags: ["Video"],
  //   aspect: "square",
  //   mediaType: "video",
  //   profileName: "Content Creator",
  //   profileIcon: "clapperboard",
  // },
  // {
  //   src: "/yeni-video.webm",
  //   alt: "Viral video örneği 2",
  //   title: "Viral Video İçerikleri",
  //   description: "Etkileşim odaklı kısa videolar",
  //   tags: ["Video"],
  //   aspect: "square",
  //   mediaType: "video",
  //   profileName: "Viral Studio",
  //   profileIcon: "sparkles",
  // },
  {
    src: mediaUrls.frame,
    alt: "Özel grafik tasarım örneği",
    title: "Özel Grafik Tasarımlar",
    description: "Dikkat çekici tasarım konseptleri",
    tags: ["Grafik"],
    aspect: "square",
    mediaType: "image",
    profileName: "Animation Pro",
    profileIcon: "star",
    country: "TR",
  },
  {
    src: mediaUrls.finalVideo,
    alt: "Logo animasyonu örneği",
    title: "Profesyonel Logo Animasyonları",
    description: "Intro / logo hareketlendirme",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "3D Studio",
    profileIcon: "code2",
    poster: mediaUrls.posters.finalVideo,
    country: "TR",
  },
  // {
  //   src: "/bentogrid-item-492.mp4",
  //   alt: "3D animasyon ve VR efektleri örneği",
  //   title: "3D Animasyon & VR Efektleri",
  //   description: "Sahne / 3D / efekt çalışmaları",
  //   tags: ["Video"],
  //   aspect: "square",
  //   mediaType: "video",
  //   profileName: "Brand Hotel",
  //   profileIcon: "lightbulb",
  // },
  {
    src: mediaUrls.tayf,
    alt: "Grafik tasarım örneği 2",
    title: "Özel Grafik Tasarımlar",
    description: "Branding / konsept tasarım",
    tags: ["Grafik"],
    aspect: "square",
    mediaType: "image",
    profileName: "Design Expert",
    profileIcon: "palette",
    country: "TR",
  },
  {
    src: mediaUrls.downloadedVideo,
    alt: "Profesyonel video içerik örneği",
    title: "Profesyonel Video İçerikler",
    description: "Çekim / kurgu / montaj",
    tags: ["Video", "Drone"],
    aspect: "square",
    mediaType: "video",
    profileName: "Pro Video Team",
    profileIcon: "code2",
    poster: mediaUrls.posters.downloadedVideo,
    country: "TR",
  },
  {
    src: mediaUrls.vimeoOriginal,
    alt: "Profesyonel video içerik örneği 2",
    title: "Profesyonel Video İçerikler",
    description: "Reklam / tanıtım videoları",
    tags: ["Video", "Drone"],
    aspect: "square",
    mediaType: "video",
    profileName: "Video Studio",
    profileIcon: "gauge",
    poster: mediaUrls.posters.vimeoOriginal,
    country: "TR",
  },
  {
    src: mediaUrls.theKreatif,
    alt: "The Kreatif ajans tanıtım videosu",
    title: "The Kreatif",
    description: "Ajans tanıtım videosu",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "The Kreatif",
    profileIcon: "sparkles",
    poster: mediaUrls.posters.theKreatif,
    country: "TR",
  },
  {
    src: mediaUrls.theKreatif2,
    alt: "The Kreatif 2 ajans tanıtım videosu",
    title: "The Kreatif 2",
    description: "Ajans tanıtım videosu",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "The Kreatif",
    profileIcon: "sparkles",
    poster: mediaUrls.posters.theKreatif2,
    country: "TR",
  },
  {
    src: mediaUrls.aradiginFirma,
    alt: "Aradığın Firma rehber videosu",
    title: "Aradığın Firma",
    description: "Firma rehberi tanıtım",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "Aradığın Firma",
    profileIcon: "rocket",
    poster: mediaUrls.posters.aradiginFirma,
    country: "TR",
  },
  {
    src: mediaUrls.paparinho,
    alt: "Paparinho restoran tanıtım videosu",
    title: "Paparinho",
    description: "Restoran tanıtım videosu",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "Paparinho",
    profileIcon: "star",
    poster: mediaUrls.posters.paparinho,
    country: "TR",
  },
    {
    src: mediaUrls.blockchain,
    alt: "Blockchain ve kripto animasyon videosu",
    title: "Blockchain & Kripto Animasyonları",
    description: "Web3 ve blockchain tanıtım videoları",
    tags: ["Video", "3D"],
    aspect: "square",
    mediaType: "video",
    profileName: "Blockchain Studio",
    profileIcon: "code2",
    country: "TR",
  },
];
