import type { GalleryPhoto } from "@/components/photos-gallery/PhotosGallerySection";

export const websiteProjectsGalleryPhotos: GalleryPhoto[] = [
  {
    src: "/Burger.mp4",
    alt: "Burger video örneği",
    title: "Burger",
    description: "Video örneği",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "Ajans 99",
    profileIcon: "video",
  },
  // {
  //   src: "/Roots.mp4",
  //   alt: "Roots video örneği",
  //   title: "Roots",
  //   description: "Video örneği",
  //   tags: ["Video"],
  //   aspect: "square",
  //   mediaType: "video",
  //   profileName: "Ajans 99",
  //   profileIcon: "video",
  // },
  {
    src: "/sosyal-medya-video.webm",
    alt: "Profesyonel sosyal medya yönetimi video örneği",
    title: "Profesyonel Sosyal Medya Yönetimi",
    description: "Kısa video örneği",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "Social Media Pro",
    profileIcon: "camera",
  },
  {
    src: "/influencer_video.webm",
    alt: "Drone tanıtım videosu örneği",
    title: "Drone Tanıtım Videoları",
    description: "Kuș bakıșı tanıtım çekimleri",
    tags: ["Video", "Drone"],
    aspect: "square",
    mediaType: "video",
    profileName: "Drone Studios",
    profileIcon: "video",
  },
  {
    src: "/video1feedbird_first13sec.mp4",
    alt: "Influencer içerik videosu örneği",
    title: "Influencer İçerik Üretimi",
    description: "UGC / Reels içerikleri",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "Influencer Creators",
    profileIcon: "sparkles",
  },
  {
    src: "/video/ticaret.webm",
    alt: "Influencer ticaret içerik videosu",
    title: "Influencer İçerik Üretimi",
    description: "UGC / Reels içerikleri",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "Influencer Creators",
    profileIcon: "sparkles",
  },
  {
    src: "/video/villa.webm",
    alt: "Influencer villa içerik videosu",
    title: "Influencer İçerik Üretimi",
    description: "UGC / Reels içerikleri",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "Influencer Creators",
    profileIcon: "sparkles",
  },
  {
    src: "/video/konut.webm",
    alt: "Influencer konut içerik videosu",
    title: "Influencer İçerik Üretimi",
    description: "UGC / Reels içerikleri",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "Influencer Creators",
    profileIcon: "sparkles",
  },
  {
    src: "/video/arsa_compressed.webm",
    alt: "Influencer arsa içerik videosu",
    title: "Influencer İçerik Üretimi",
    description: "UGC / Reels içerikleri",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "Influencer Creators",
    profileIcon: "sparkles",
  },
  {
    src: "/TRr.png",
    alt: "Grafik tasarım örneği",
    title: "Özel Grafik Tasarımlar",
    description: "Markaya özel görsel çalışmalar",
    tags: ["Grafik"],
    aspect: "square",
    mediaType: "image",
    profileName: "Design Studio",
    profileIcon: "palette",
  },
  {
    src: "/video4_noaudio_trimmed.webm",
    alt: "Viral video animasyon örneği",
    title: "Viral Video İçerikleri",
    description: "Animasyon / reklam içerikleri",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "Content Creator",
    profileIcon: "clapperboard",
  },
  // {
  //   src: "/yeni-video.webm",
  //   alt: "Viral video örneği 2",
  //   title: "Viral Video İçerikleri",
  //   description: "Etkileşim odaklı kısa videolar",
  //   tags: ["Video"],
  //   aspect: "square",
  //   mediaType: "video",
  //   profileName: "Viral Studio",
  //   profileIcon: "sparkles",
  // },
  {
    src: "/new-video.webm",
    alt: "Viral video örneği 3",
    title: "Viral Video İçerikleri",
    description: "Kurgu / efekt / montaj",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "Graphic Designer",
    profileIcon: "rocket",
  },
  {
    src: "/frame.png",
    alt: "Özel grafik tasarım örneği",
    title: "Özel Grafik Tasarımlar",
    description: "Dikkat çekici tasarım konseptleri",
    tags: ["Grafik"],
    aspect: "square",
    mediaType: "image",
    profileName: "Animation Pro",
    profileIcon: "star",
  },
  {
    src: "/final_video.mp4",
    alt: "Logo animasyonu örneği",
    title: "Profesyonel Logo Animasyonları",
    description: "Intro / logo hareketlendirme",
    tags: ["Video"],
    aspect: "square",
    mediaType: "video",
    profileName: "3D Studio",
    profileIcon: "code2",
  },
  // {
  //   src: "/bentogrid-item-492.mp4",
  //   alt: "3D animasyon ve VR efektleri örneği",
  //   title: "3D Animasyon & VR Efektleri",
  //   description: "Sahne / 3D / efekt çalışmaları",
  //   tags: ["Video"],
  //   aspect: "square",
  //   mediaType: "video",
  //   profileName: "Brand Hotel",
  //   profileIcon: "lightbulb",
  // },
  {
    src: "/tayf.png",
    alt: "Grafik tasarım örneği 2",
    title: "Özel Grafik Tasarımlar",
    description: "Branding / konsept tasarım",
    tags: ["Grafik"],
    aspect: "square",
    mediaType: "image",
    profileName: "Design Expert",
    profileIcon: "palette",
  },
  // {
  //   src: "/downloaded_video.mp4",
  //   alt: "Profesyonel video içerik örneği",
  //   title: "Profesyonel Video İçerikler",
  //   description: "Çekim / kurgu / montaj",
  //   tags: ["Video", "Drone"],
  //   aspect: "square",
  //   mediaType: "video",
  //   profileName: "Pro Video Team",
  //   profileIcon: "code2",
  // },
  {
    src: "/vimeo-video-original.mp4",
    alt: "Profesyonel video içerik örneği 2",
    title: "Profesyonel Video İçerikler",
    description: "Reklam / tanıtım videoları",
    tags: ["Video", "Drone"],
    aspect: "square",
    mediaType: "video",
    profileName: "Video Studio",
    profileIcon: "gauge",
  },
];
